site:
  title: AsciiDoc Demo
  url: https://janiveer.github.io/lightweight-markup
  start_page: home::index.adoc
content:
  branches: HEAD
  sources:
  - url: .
    branches: HEAD
    start_path: home
asciidoc:
  attributes:
    experimental: ''
    idprefix: '@'
    idseparator: '-@'
    tabs: tabs
    toc: ~
    xrefstyle: short
  extensions:
  - ./lib/json-config-ui-block-macro.js
  - ./lib/man-inline-macro.js
  - ./lib/multirow-table-head-tree-processor.js
  - ./lib/swagger-ui-block-macro.js
  - ./lib/tabs-block.js
ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/master/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true
output:
  dir: ./public
