= Overview

PACBook enables you to:

[[Home-Trans]]
Transclusion stylesheets
------------------------

1.  Perform parametrised transclusion …
xref:transclusion:TransParam.xsl.adoc[TransParam.xsl]
2.  Fix up duplicate IDs … xref:transclusion:TransID.xsl.adoc[TransID.xsl]
3.  Fix up links to duplicate IDs or links to non-existent targets …
xref:transclusion:TransLinks.xsl.adoc[TransLinks.xsl]

[[Home-Ling]]
Linguistic stylesheets
----------------------

1.  Select the correct form of transcluded terms, depending on their
syntactic environment … xref:linguistic:LingHead.xsl.adoc[LingHead.xsl]
2.  Inflect text which depends syntactically on any transcluded terms …
xref:linguistic:LingDepend.xsl.adoc[LingDepend.xsl]
3.  Select the correct orthographic case for text, depending on
environment … xref:linguistic:LingCasing.xsl.adoc[LingCasing.xsl]

[[Home-Text]]
Text stylesheets
----------------

1.  Punctuate abbreviations correctly so they don’t have two full stops
at the end of a sentence … xref:text:TextAbbrev.xsl.adoc[TextAbbrev.xsl]
2.  Localise number formatting … xref:text:TextNumbers.xsl.adoc[TextNumbers.xsl]

[[Home-DB]]
DocBook stylesheets
-------------------

1.  Resolve image references against xml:base …
xref:docbook:DBImage.xsl.adoc[DBImage.xsl]
2.  Resolve image references against the XML Catalog …
xref:docbook:RefResolve.xsl.adoc[RefResolve.xsl]
3.  Perform enhanced DocBook conditional profiling …
xref:docbook:DBProfile.xsl.adoc[DBProfile.xsl]
4.  Create automatic titles for DocBook admonitions …
xref:docbook:DBAdmon.xsl.adoc[DBAdmon.xsl]
5.  Perform enhanced formatting of DocBook simple lists — select the
correct form of conjunctions based on the phonetic environment, for
languages which demand it … xref:docbook:DBLists.xsl.adoc[DBLists.xsl]
6.  Create revision history and applicability tables based on the
document metadata … xref:docbook:DBProcs.xsl.adoc[DBProcs.xsl]
7.  Perform enhanced DocBook glossary processing — include terms in the
glossary if they are referred to by other terms …
xref:docbook:DBGloss.xsl.adoc[DBGloss.xsl]
8.  Create automatic links between DocBook sections, based on shared
labels … xref:docbook:DBRels.xsl.adoc[DBRels.xsl]

[[Home-Xlate]]
Translation stylesheets
-----------------------

1.  Translate the document using a single XLIFF file …
xref:translation:XlateConvert.xsl.adoc[XlateConvert.xsl]
2.  Create multilingual translations, using several XLIFF files …
xref:translation:XlateCombine.xsl.adoc[XlateCombine.xsl]
3.  Fix up IDs in multilingual translations …
xref:translation:XlateID.xsl.adoc[XlateID.xsl]
4.  Mark up elements in a file for translation …
xref:translation:XlateMarkup.xsl.adoc[XlateMarkup.xsl]
5.  Extract translation elements to an XLIFF file …
xref:translation:XlateExtract.xsl.adoc[XlateExtract.xsl]
6.  Compare document to existing XLIFF file and create diff file …
xref:translation:XlateDiff.xsl.adoc[XlateDiff.xsl]
7.  Merge new translation units into existing XLIFF file …
xref:translation:XlateMerge.xsl.adoc[XlateMerge.xsl]

[[Home-Xliff]]
XLIFF management stylesheets
----------------------------

1.  Remove duplicate translation units from XLIFF file …
xref:xliff:XliffDupe.xsl.adoc[XliffDupe.xsl]
2.  Remove completed translation units from XLIFF file …
xref:xliff:XliffPurge.xsl.adoc[XliffPurge.xsl]
3.  Escape inline markup in an XLIFF file …
xref:xliff:XliffRaw.xsl.adoc[XliffRaw.xsl]
4.  Unescape inline markup in an XLIFF file …
xref:xliff:XliffTemp.xsl.adoc[XliffTemp.xsl], xref:xliff:XliffTag.xsl.adoc[XliffTag.xsl]
5.  Export an XLIFF file to CSV … xref:xliff:Xliff2CSV.xsl.adoc[Xliff2CSV.xsl]
6.  Import from Microsoft Excel XML to XLIFF …
xref:xliff:XL2Xliff.xsl.adoc[XL2Xliff.xsl]

[NOTE]
--
PACBook also provides a xref:introduction:PACBook-Schema.adoc[custom schema] to enable
all of these features in DocBook 5.0.

It’s important to note that PACBook is not a natural language processor.
The author or translator must mark up text for linguistic processing by
hand.
--
