= XlateMerge.xsl
:RDF-Translations: xref:introduction:RDF-Translations.adoc
:xliff: http://docs.oasis-open.org/xliff/v1.2/os/xliff-core.html

[abstract]
Checks an XML document against an existing translation and a differential translation in the specified language and generates a new XLIFF file merging the two translations.

== Parameters

 (Language | Xliff) Diff

`Language` (string):: ISO language code
`Xliff` (URI):: The URI of the original {xliff}[XLIFF] file
`Diff` (URI):: The URI of the differential {xliff}[XLIFF] file

== Input
An XML document. You must mark up the source document with:

. The xlf:id attributes which uniquely identify each translation string.
. Optionally, {RDF-Translations}[translation metadata], showing the location of the {xliff}[XLIFF] files which contain the translations of the document — this is only required if you are not specifying the `Xliff` parameter explicitly.

== Output
An {xliff}[XLIFF] document.

== Description
The stylesheet examines the source file for translatable elements.
(A translatable element is one which has an xlf:id attribute and does not have the its:translate='no' attribute.)

For each translatable element, the stylesheet searches the differential {xliff}[XLIFF] file for the translation unit with the same xlf:id.
If found, and if the target of the translation unit has the attribute status='translated', this translation unit is copied to the output.

If the translation unit is not found in the differential {xliff}[XLIFF] file, the stylesheet looks for the specified original {xliff}[XLIFF] file, or if not specified, the {xliff}[XLIFF] file that corresponds to the specified output language, according to the {RDF-Translations}[translation metadata].

If the original {xliff}[XLIFF] file is found, the stylesheet searches for the translation unit with the same xlf:id.
If found, this translation unit is copied to the output.

If the corresponding translation unit does not exist in the differential {xliff}[XLIFF] file or the original {xliff}[XLIFF] file, there is no output.

If the original {xliff}[XLIFF] file is not found, there is no output.

NOTE: In the output file, all trans-unit elements are contained in a single, flat file element.
Any multiple file or group elements from the original or differential {xliff}[XLIFF] files are not copied to the output file.
