= XlateMerge.xsl

[abstract]
Checks an XML document against an existing translation and a
differential translation in the specified language and generates a new XLIFF
file merging the two translations.

== Parameters

 (Language | Xliff) Diff

`Language` (string):: ISO language code,
`Xliff` (URI):: The URI of the original
http://docs.oasis-open.org/xliff/v1.2/os/xliff-core.html[XLIFF] file
`Diff` (URI):: The URI of the differential
http://docs.oasis-open.org/xliff/v1.2/os/xliff-core.html[XLIFF] file

== Input
An XML document. You must mark up the source document with:

. The xlf:id attributes which uniquely identify each translation
string.
. Optionally, link:#RDF-Translations[translation metadata], showing
the location of the
http://docs.oasis-open.org/xliff/v1.2/os/xliff-core.html[XLIFF] files
which contain the translations of the document — this is only required
if you are not specifying the `Xliff` parameter explicitly.

== Output
An http://docs.oasis-open.org/xliff/v1.2/os/xliff-core.html[XLIFF]
document.

== Description
The stylesheet examines the source file for translatable elements. (A
translatable element is one which has an xlf:id attribute and does not
have the its:translate='no' attribute.)

For each translatable element, the stylesheet searches the differential
http://docs.oasis-open.org/xliff/v1.2/os/xliff-core.html[XLIFF] file for
the translation unit with the same xlf:id. If found, and if the target
of the translation unit has the attribute status='translated', this
translation unit is copied to the output.

If the translation unit is not found in the differential
http://docs.oasis-open.org/xliff/v1.2/os/xliff-core.html[XLIFF] file,
the stylesheet looks for the specified original
http://docs.oasis-open.org/xliff/v1.2/os/xliff-core.html[XLIFF] file, or
if not specified, the
http://docs.oasis-open.org/xliff/v1.2/os/xliff-core.html[XLIFF] file
that corresponds to the specified output language, according to the
link:#RDF-Translations[translation metadata].

If the original
http://docs.oasis-open.org/xliff/v1.2/os/xliff-core.html[XLIFF] file is
found, the stylesheet searches for the translation unit with the same
xlf:id. If found, this translation unit is copied to the output.

If the corresponding translation unit does not exist in the differential
http://docs.oasis-open.org/xliff/v1.2/os/xliff-core.html[XLIFF] file or
the original
http://docs.oasis-open.org/xliff/v1.2/os/xliff-core.html[XLIFF] file,
there is no output.

If the original
http://docs.oasis-open.org/xliff/v1.2/os/xliff-core.html[XLIFF] file is
not found, there is no output.

NOTE: In the output file, all trans-unit elements are contained in a single,
flat file element. Any multiple file or group elements from the original
or differential
http://docs.oasis-open.org/xliff/v1.2/os/xliff-core.html[XLIFF] files
are not copied to the output file.
