= PACBook Schema

Not all of PACBook’s features are natively available in DocBook 5.0.
PACBook provides a custom RelaxNG schema to enable them.

`pacbook.rng` adds the following features to the DocBook 5.0
`docbookxi.rng` schema.

[[PACBook-Schema-Elements]]
Elements
--------

`pacbook.rng` adds the following elements in the DocBook namespace.

* An optional title element as an initial child of the extendedlink
element. This can contain text and all inline elements. It takes all
common DocBook attributes. By default the xl:type attribute is set to
title. This element enables you to define a title for an extended link.
* Any number of optional resource elements within the extendedlink
element. This can contain text, all block elements and all inline
elements. It takes all common DocBook attributes. By default the xl:type
attribute is set to resource. This element enables you to define a
resource in an extended link.

[[PACBook-Schema-Attributes]]
Attributes
----------

`pacbook.rng` adds the following to the DocBook common attributes.

* All ITS 2.0 local attributes in the http://www.w3.org/TR/its20/[ITS]
namespace.
* The xlf:id attribute. This is in the
http://docs.oasis-open.org/xliff/v1.2/os/xliff-core.html[XLIFF]
namespace and contains an NMToken. It is used for PACBook translation —
see xref:translation:XlateMarkup.xsl.adoc[XlateMarkup.xsl].
* The content:ref attribute. This is in the
http://stanleysecurity.github.io/PACBook/ns/transclusion[PACBook
transclusion] namespace and contains an NMToken. It is used for
parametrised transclusion — see xref:transclusion:TransParam.xsl.adoc[TransParam.xsl].
* The following linguistic markup attributes. They are in the
http://stanleysecurity.github.io/PACBook/ns/linguistics[PACBook
linguistics] namespace and contain NMTokens. They are used for
linguistic pre-processing.
+
ling:type — marks government and binding. Set to head for inflected head
nouns, depend for inflected dependent words. See
xref:linguistic:LingHead.xsl.adoc[LingHead.xsl], xref:linguistic:LingDepend.xsl.adoc[LingDepend.xsl].
+
ling:pron — marks pronunciation of a head word. See
xref:linguistic:LingDepend.xsl.adoc[LingDepend.xsl].
+
ling:gen — marks syntactic gender. See
xref:linguistic:LingDepend.xsl.adoc[LingDepend.xsl].
+
ling:num — marks syntactic number. See
xref:linguistic:LingDepend.xsl.adoc[LingDepend.xsl].
+
ling:case — marks syntactic case. See lxref:linguistic:LingHead.xsl.adoc[LingHead.xsl],
xref:linguistic:LingDepend.xsl.adoc[LingDepend.xsl].
+
ling:class — marks syntactic definiteness. See
xref:linguistic:LingHead.xsl.adoc[LingHead.xsl], xref:linguistic:LingDepend.xsl.adoc[LingDepend.xsl].
+
ling:orth — marks orthographic case. See
xref:linguistic:LingCasing.xsl.adoc[LingCasing.xsl].

NOTE: PACBook also adds the outputformat attribute in the DocBook namespace as
a common attribute. This is due to be added in DocBook 5.1 anyway; I’ve
added it to PACBook because I found it useful.
